#!/bin/bash

# Script to make a new Security Adminstrator named "bob" that is the linux user and mapping him to the staff_u selinux user, and also assigning them the secadm role


sudo useradd bob
sudo passwd bob
sudo semanage login -a -s staff_u -r s0-s0:c0.c1023 bob
sudo semanage user -m -R "staff_r secadm_r sysadm_r system_r" staff_u
